M48
; DRILL file {KiCad (6.0.10)} date Fri Feb 17 09:16:24 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T09:16:24-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.4Y-3.8
X5.6Y-3.8
X5.7Y-3.7
X5.7Y-4.0
X5.8Y-4.0
X6.0Y-3.6
X6.1Y-3.9
X6.2Y-3.7
X6.2Y-4.3
X6.3Y-3.3
T2
X5.8Y-3.2
X6.0Y-3.2
T0
M30
